language: python
sudo: false
os:
  - linux

python:
  - "3.6"

install:
  - pip install -r dev-requirements.txt

script:
  - "PYTHONPATH=django_todos py.test -v --tb=short tests/"

notifications:
  webhooks:
    urls:
      - https://rmotr.com/api/v1/webhooks/travis/build-project
    on_success: always
    on_failure: always
    on_start: never
